api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    exception_to_status:
        App\Exception\InvalidConfirmationTokenException: 404

    collection:
        pagination:
    #        enabled: false
            page_parameter_name: _page
            items_per_page: 20
#            partial: true
#            client_partial: true
#            partial_parameter_name: 'partial'