easy_admin:
  entities:
    BlogPost:
      class: App\Entity\BlogPost
      list:
        actions: [ { name: 'show' } ]
      show:
        fields:
          - title
          - published
          - content
          - author
          - commments
    User:
      class: App\Entity\User
    Comment:
      class: App\Entity\Comment
    Image:
      class: App\Entity\Image