services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Behatch\HttpCall\Request:
        arguments:
            - '@behat.mink'
        public: false